# Generated by Django 6.0.5 on 2026-05-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codereview",
            name="improved_code",
            field=models.TextField(
                blank=True, help_text="AI suggested corrected code version", null=True
            ),
        ),
    ]
